config/routes.rb
Rails.application.routes.draw do
  resources :data
  resources :shops
  resources :products
  resources :categories do
    resources :products, only: [:index] do
      resources :data, only: [:index]
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/datum.rb
class Datum < ApplicationRecord
  belongs_to :product
  belongs_to :shop
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
end

app/models/shop.rb
class Shop < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories
  def index
    @categories = Category.all
  end

  # GET /categories/1
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path, notice: "Category was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /categories/1
  def update
    if @category.update(category_params)
      redirect_to categories_path, notice: "Category was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /categories/1
  def destroy
    @category.destroy!
    redirect_to categories_url, notice: "Category was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/data_controller.rb
class DataController < ApplicationController
  before_action :set_datum, only: %i[ show edit update destroy ]

  # GET /data
  def index
    @category_id = Category.exists?(id: params[:category_id]) ? params[:category_id] : nil
    @data = params[:product_id].present? ? Datum.where(product_id: params[:product_id]).order(date: :desc) : Datum.all
  end

  # GET /data/1
  def show
  end

  # GET /data/new
  def new
    @category_id = Category.exists?(id: params[:category_id]) ? params[:category_id] : nil
    @product_id = Product.exists?(id: params[:product_id]) ? params[:product_id] : nil
    @datum = Datum.new
  end

  # GET /data/1/edit
  def edit
  end

  # POST /data
  def create
    @datum = Datum.new(datum_params)

    if @datum.save
      redirect_to category_product_data_path(category_id: @datum.product.category_id, product_id: @datum.product_id), notice: "Datum was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /data/1
  def update
    if @datum.update(datum_params)
      redirect_to category_product_data_path(category_id: @datum.product.category_id, product_id: @datum.product_id), notice: "Datum was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /data/1
  def destroy
    @datum.destroy!
    redirect_to data_url, notice: "Datum was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datum
      @datum = Datum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def datum_params
      params.require(:datum).permit(:price, :date, :product_id, :shop_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products
  def index
    @products = params[:category_id].present? ? Product.where(category_id: params[:category_id]) : Product.all
  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @category_id = Category.exists?(id: params[:category_id]) ? params[:category_id] : nil
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @category_id = @product.category_id
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to category_products_path(category_id: @product.category_id), notice: "Product was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to category_products_path(category_id: @product.category_id), notice: "Product was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy!
    redirect_to products_url, notice: "Product was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :supplement, :category_id)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: %i[ show edit update destroy ]

  # GET /shops
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  def create
    @shop = Shop.new(shop_params)

    if @shop.save
      redirect_to @shop, notice: "Shop was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /shops/1
  def update
    if @shop.update(shop_params)
      redirect_to @shop, notice: "Shop was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /shops/1
  def destroy
    @shop.destroy!
    redirect_to shops_url, notice: "Shop was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shop_params
      params.require(:shop).permit(:name, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/data_helper.rb
module DataHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= category.name %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this category", category, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this category", edit_category_path(category), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/categories/admin_index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Categories</h1>
    <%= link_to "New category", new_category_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="categories" class="min-w-full">
    <%= render @categories %>
  </div>
</div>

app/views/categories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Categories</h1>
    <%= link_to "New category", new_category_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
  <div class="mt-5">
    <table class="divide-y divide-gray-200 dark:divide-neutral-700">
      <thead>
      </thead>
      <tbody class="divide-y divide-gray-200 dark:divide-neutral-700">
        <% @categories.each do |category| %>
          <tr>
            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 dark:text-neutral-200">
              <%= link_to category.name, category_products_path(category_id: category.id) %>
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 dark:text-neutral-200">
              <%= link_to "Show products", category_products_path(category_id: category.id), class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 dark:text-neutral-200">
              <%= link_to "Edit", edit_category_path(category), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/categories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @category %>

    <%= link_to "Edit this category", edit_category_path(@category), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this category", category_path(@category), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/data/_datum.html.erb
<div id="<%= dom_id datum %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Price:</strong>
    <%= datum.price %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Date:</strong>
    <%= datum.date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Product:</strong>
    <%= datum.product_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Shop:</strong>
    <%= datum.shop_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this datum", datum, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this datum", edit_datum_path(datum), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/data/_form.html.erb
<%= form_with(model: datum, class: "contents") do |form| %>
  <% if datum.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(datum.errors.count, "error") %> prohibited this datum from being saved:</h2>

      <ul>
        <% datum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :product_id %>
    <%= form.collection_select :product_id, Product.all, :id, :name, { prompt: "", selected: @product_id }, { class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" } %>
  </div>

  <div class="my-5">
    <%= form.label :shop_id %>
    <%= form.collection_select :shop_id, Shop.all, :id, :name, { prompt: ""  }, { class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" } %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.number_field :price, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :date %>
    <%= form.date_field :date, value: Date.today, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/data/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing datum</h1>

  <%= render "form", datum: @datum %>

  <%= link_to "Back to home", root_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/data/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% if @data.exists? %>
    <div class="flex justify-between items-center">
      <h1 class="font-bold text-4xl"><%= @data.first.product.name %></h1>
      <div class="flex items-container">
        <%= link_to "Back to products", category_products_path(category_id: @category_id), class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
        <%= link_to "New datum", new_datum_path(category_id: @category_id, product_id: @data&.first&.product&.id), class: "rounded-lg ml-5 py-3 px-5 bg-blue-600 text-white block font-medium" %>
      </div>
    </div>

    <div id="data" class="min-w-full mt-5">
      <table class="divide-y divide-gray-200 dark:divide-neutral-700">
        <thead>
          <tr>
            <th>Date</th>
            <th>Price</th>
            <th>Shop name</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-gray-200 dark:divide-neutral-700">
          <% @data.each do |d| %>
            <tr>
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 dark:text-neutral-200">
                <%= d.date %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 dark:text-neutral-200">
                <%= number_to_currency(d.price, unit: "円", precision: 0, format: "%n%u" ) %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 dark:text-neutral-200">
                <%= d.shop.name %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <div class="flex justify-between items-center">
      <h1 class="font-bold text-4xl">No Data</h1>
      <div class="flex items-container">
        <%= link_to "Back to products", category_products_path(category_id: @category_id), class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
        <%= link_to "New datum", new_datum_path(product_id: @data&.first&.product&.id), class: "rounded-lg ml-5 py-3 px-5 bg-blue-600 text-white block font-medium" %>
      </div>
    </div>
  <% end %>
</div>

app/views/data/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New datum</h1>

  <%= render "form", datum: @datum %>

  <% if @product_id %>
    <%= link_to "Back to data", category_product_data_path(category_id: @category_id, product_id: @product_id), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <% else %>
    <%= link_to "Back to home", root_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <% end %>
</div>

app/views/data/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @datum %>

    <%= link_to "Edit this datum", edit_datum_path(@datum), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this datum", datum_path(@datum), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to home", root_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/home/_category.html.erb
<div id="<%= dom_id category %>">
  <p class="my-5">
    <%= link_to category.name, category_products_path(category_id: category.id), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </p>
</div>

app/views/layouts/_header.html.erb
<header class="text-gray-200 body-font bg-blue-600 sticky top-0">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <%= link_to "PriCom", root_path, class: "flex title-font font-medium items-center text-gray-50 mb-4 md:mb-0 ml-3 text-xl" %>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      <%= link_to "Categories", categories_path, class: "mr-5 hover:text-gray-50" %>
      <%= link_to "Products", products_path, class: "mr-5 hover:text-gray-50" %>
      <%= link_to "Shops", shops_path, class: "mr-5 hover:text-gray-50" %>
    </nav>
  </div>
</header>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= product.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Supplement:</strong>
    <%= product.supplement %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Category:</strong>
    <%= product.category_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this product", product, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this product", edit_product_path(product), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/products/_product_detail.html.erb
<div id="<%= dom_id product %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= product.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Supplement:</strong>
    <%= product.supplement %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Category:</strong>
    <%= product.category_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this product", product, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this product", edit_product_path(product), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/products/admin_index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Products</h1>
    <%= link_to "New product", new_product_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="products" class="min-w-full">
    <%= render @products %>
  </div>
</div>

app/views/products/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl"><%= "All " if params[:category_id].blank? %>Products</h1>
    <div class="flex items-container">
      <%= link_to "Back to categories", categories_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
      <%= link_to "New product", new_product_path(category_id: @products&.first&.category_id), class: "rounded-lg ml-5 py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>
  </div>

  <div id="products" class="min-w-full mt-5">
    <table class="divide-y divide-gray-200 dark:divide-neutral-700">
      <thead>
      </thead>
      <tbody class="divide-y divide-gray-200 dark:divide-neutral-700">
        <% @products.each do |product| %>
          <tr>
            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 dark:text-neutral-200">
              <%= link_to product.name, category_product_data_path(category_id: product.category_id, product_id: product.id) %>
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 dark:text-neutral-200">
              <%= link_to "Show data", category_product_data_path(category_id: product.category_id, product_id: product.id), class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
            </td>
            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 dark:text-neutral-200">
              <%= link_to "Edit", edit_product_path(product), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/products/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render "product_detail", product: @product %>

    <%= link_to "Edit this product", edit_product_path(@product), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this product", product_path(@product), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to products", products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/shops/_shop.html.erb
<div id="<%= dom_id shop %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= shop.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Address:</strong>
    <%= shop.address %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this shop", shop, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this shop", edit_shop_path(shop), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/shops/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing shop</h1>

  <%= render "form", shop: @shop %>

  <%= link_to "Show this shop", @shop, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to shops", shops_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/shops/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Shops</h1>
    <%= link_to "New shop", new_shop_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="shops" class="min-w-full">
    <%= render @shops %>
  </div>
</div>

app/views/shops/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New shop</h1>

  <%= render "form", shop: @shop %>

  <%= link_to "Back to shops", shops_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/shops/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @shop %>

    <%= link_to "Edit this shop", edit_shop_path(@shop), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this shop", shop_path(@shop), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to shops", shops_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>